language: go
go:
  - 1.7
before_install:
  - go get -u github.com/kardianos/govendor
before_script:
  - go get -d ./...
script:
  - govendor sync
  - go get github.com/ethereum/go-ethereum #seems to have conflicts with govendor on travis ci
  - go build cmd/agent_main.go
  - go test ./...